## Basic Configuration

baseurl = "https://jcsi.ms" #Example "https://<you>.github.io/"  
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Chris Sims"
title = "Chris Sims"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "<yourDisqusShortName>" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Chris Sims"
intro = "Software Engineer"
description = "Writing Clojure and wrapping my head around distributed systems"
authorImage = "headshot.jpeg"
dateFormat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal website of Chris Sims"
keywords = "chris sims"

## Social Accounts
[params.social]
github = "jcsims"
#instagram = "<username>"
linkedIn = "jcsims1"
twitter = "jcsims"
#facebook = "<username>"
#google = "<username>"
email = "chris@jcsi.ms"

## Extras
[params.extra]
copyright = "© 2016. Chris Sims. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredBy = false
hightlightJS = true

## Main Menu
[[menu.main]]
    name = "posts"
    weight = 100
    identifier = "posts"
    url = "/post/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
